name = "SPH"

[build]
auto-executables = false
auto-tests       = false
auto-examples    = false

[library]
include-dir = "src"

[[executable]]
name        = "sph"
source-dir  = "app"
main        = "sph.f90"