name = "SPH"

[build]
auto-executables = false
auto-tests       = false
auto-examples    = false

[library]
include-dir = "src"

[[executable]]
name = "sph"
main = "sph.f90"
source-dir  = "app"

[[test]]
name = "tester"
main = "tester.f90"
source-dir = "test"